title: Alpaca DeVlog
email: hs88610@gmail.com
description: The result oriendted, Communicational, Challenger
author: 박한성
# baseurl:           "/startbootstrap-clean-blog-jekyll"
baseurl: ''
url: 'https://parkhanseong.github.io'

# Social Profiles
twitter_username: none
github_username: parkhanseong
facebook_username: 박한성

# Build settings
markdown: kramdown
paginate: 5
paginate_path: '/posts/page:num/'
plugins:
  - jekyll-feed
  - jekyll-paginate
